version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: facesocial-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Boss.1212
      POSTGRES_DB: facesocial
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: facesocial-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
